export default en = {
  hallSize: 'Hall size',
  otherDetails: 'Other Details',
  servicePlace: 'Service Place',
  serviceProvider: 'Service Provider',
  course: 'Course',
  serviceType: 'Service type',
  featuresNotAllowed: 'This feature is not availabe for your account type',
  canceled: 'Canceled',
  repeat: 'Repeat',
  joinRequest: 'join Request',
  joinRequests: 'Join Requests',
  phone: 'Phone',
  codeSentTo: 'Activation code sent to ',
  accountNotRegistered: 'Account is not registered',
  dontWorryRestorepassword: 'Dont worry, enter your',
  chooseHowToRestore: 'Choose how to restore your credentials',
  justEnterEmailAndPass: 'Enter your informations',
  employer: 'Employer',
  companyActivity: 'Company Activity',
  tradeName: 'Company trade name',
  workplace: 'workplace',
  employeeLevel: 'Employee Level',
  userNameFull: 'User NameFull',
  hallProvider: 'Hall Provier',
  coach: 'coach',
  user: 'User',
  signAs: 'Sign up As',
  organization: 'Company',
  chooseAcountType: 'Choose Account Type',
  hiAgain: 'Hi Again!',
  courseTitle: 'Course Title',
  courseRequest: 'Course Request',
  startTime: 'Start Time',
  endTime: 'End Time',
  pickLocation: 'Pick Location',
  featuresEn: 'Features in english',
  featuresAr: 'Features in arabic',
  addressEn: 'Address in english',
  addressAr: 'Address in arabic',
  yourArName: 'Your arabic name',
  attachPhoto: 'Attach Photo',
  courseLink: 'Course Link',
  offerCost: 'Offer Cost',
  notAvailable: 'Not Available',
  available: 'Available',
  status: 'Status',
  englishDetails: 'English Details',
  appNeedPhotoPermission: 'App need photo permission',
  feildsWithStarRequierd: 'All * Feild Requeired',
  registerNewCourse: 'Add Course',
  registerNewHall: 'Add Hall',
  weekly: 'weekly',
  monthly: 'monthly',
  annually: 'annually',
  getDayForFree: 'Get Day For Free',
  getWeekForFree: 'Get Week For Free',
  getmonthForFree: 'Get Month For Free',
  newCourse: 'New course added',
  skip: 'skip',
  haveQuestion: 'Have question, let us know',
  privacyPolicy: 'Privacy Policy',
  askConsultation: 'Ask Consultation',
  changeLang: 'Change language',
  ertaqeeapp: 'Ertaqee app, for educational services',
  contactInfo: 'contactInfo',
  workDates: 'Work Dates',
  centerActivity: 'Center Activity',
  family_name: 'Last name',
  second_name: 'Second name',

  first_name: 'First name',
  payment: 'Payment',
  totalSum: 'Total Sum',
  valueAdded: 'Value added tax',
  bestnottodisclose: 'Prefer not to disclose',
  trainees: 'Trainees',
  add_trainee: 'Add Trainee',
  discountpercentage: 'Discount Percentange',
  oldPrice: 'Old price',
  cart: 'Cart',
  cartEmpty: 'Cart Empty',
  includes: 'Me includes',
  quantity: 'quantity',
  type: 'type',
  fav: 'Favorites',
  savedCourses: 'Saved Halls',
  myReservtions: 'My reservtions',
  reservtions: 'Reservtions',
  newCourses: 'New Courses',
  worksFor: 'Works for',
  pickReservationsDate: 'Pick Reservations Date',
  hallFeatures: 'Hall features',
  person: 'Person',
  capcityfor: 'indiviuals capacity',
  addMeToCourse: 'Add me to course',
  addNewStudent: 'Add new student',
  addReservationtoCart: 'Add reservation to cart',
  evalute: 'Evaluate',
  menAndWomen: 'Men & Women',
  mensOnly: 'Men',
  womensOnly: 'Women',
  hallsOfCenter: 'Halls in the center',
  trainerName: 'Trainer Name',
  numberOfHallsinCenter: 'Number of hall in center',
  country: 'Country',
  center: 'Center',
  numberOfIndividuals: 'Number of individuals',
  hallNumber: 'Hall Number',
  aboutTrainer: 'About Trainer',
  hall: 'Hall',
  noOfDaysWeekly: 'Number of days weekly',
  noOfDays: 'Number of days',
  cost: 'Cost',
  cost1: 'Cost in riyals',
  remoteCourse: 'Remote Course',
  studentEvalute: 'Students Evalutation',
  thereIsCertificate: 'There is certificate',
  aboutCourse: 'About Course',
  number_of_hours: 'Number of hours of the course',
  courseDate: 'Course Date',
  trainingCentersFollow: 'Training center that follow',
  typeOfCourse: 'Type of course',
  newSign: 'New SignUp',
  enterYourDetails: 'Enter your details to complete registration',
  addYourNewInfoToUpdate: 'Add Your New Info To Update',
  updateProfile: 'Update Profile',
  addNumberToreceiveActivate: 'Add phone number to recivie activation message',
  welcomeAboard: 'Welcome Aboard',
  noCities: 'There is no cities added to this country',
  name: 'Name',
  myPhoto: 'My Photo',
  profile: 'Profile',
  hallName: 'Hall Name',
  consultants: 'consultations',
  subs: 'Subscriptions',
  Ads: 'Ads',
  moreOptions: 'More options',
  halls: 'Halls',
  courses: 'Courses',
  addedCourses:'Added courses',
  trainers: 'Trainers',
  reservations: 'Reservations',
  reservation: 'Reservation',
  topTrainers: 'Trainers',
  SAR: 'SAR',
  noMajor: 'No major',
  BestCenters: 'Training centers',
  trainingCenters: 'Training Centers',
  trainingcenter: 'Training Center',
  specifywhatyouneed: 'Specify what you need',
  courseName: 'Course name',
  yourcoachandcenter: 'Courses',
  namesSearchFor: 'Names, search for ',
  rewritePass: 'Rewrite Password',
  activationCode: 'Activation Code',
  enterActivationCode: 'Enter activation code',
  restorepassword: 'Restore Password',
  userName: 'UserName',
  taskCompleted: 'Task Completed',
  signIn: 'Sign In',
  statistics: 'statistics',
  eventDayIsNotToday: 'Appointment date is not today',
  entern: 'entern',
  codeSentWithMSG: 'Password Sent To Your Mobile',
  docCode: 'Doctor Code',
  searchViaDoctorCode: 'Search Via Doctor Code',
  enterDoctorCode: 'Enter Doctor Code',
  codeNotValid: 'Code Not Valid',
  drugs: 'Drugs',
  diseases: 'Diseases',
  yourEnName: 'English Name',
  needMaleOrFemaleDoctor: 'Want Male Dentist - Want Female Dentist',
  confirmPaitentArrival: 'Confirm Arrival',
  patientPhone: 'Patient Phone',
  doctorPhone: 'Doctor Phone',
  photoAttachedSuccessfully: 'Photo Attached Successfully',
  alert: 'Alert',
  startDate: 'Start Date',
  endDate: 'End Date',
  frequentDate: 'Frequent Date',
  hour: 'Hour',
  addTable: 'Add Date Table',
  followerName: 'Follower Name',
  cancelAppointment: 'Cancel Appointment',
  confirmArrival: 'Confirm Arrival',
  preferences: 'Preferences',
  rememberMe: 'Remember Me',
  allFeildsRequeired: 'All fields are required',
  feildRequeired: 'This field is required',
  feildRequeiredOrSignedBefore: 'This field is taken/required',
  followers: 'Followers',
  send: 'Send',
  noAvailableDates: 'No Available Dates',
  pickDateFirst: 'Pick Date First',
  date: 'Date',
  availableDates: 'Available Dates',
  noDataToShow: 'There is no data to display',
  back: 'Back',
  none: 'None',
  pending: 'Pending Approval',
  approved: 'Approved By Doctor',
  approvedPatient: 'Approved By Patient',
  approvePatientArrive: 'Confirm Patient Arrival',
  degree: 'Degree',
  toothPhoto: 'Tooth Photo',
  photo: 'Photo',
  somthingWentWrong: 'Somthing Went Wrong',
  entervaliddata: 'Please enter Valid Data',
  ordersenttodoctor:
    'The appointment request has been sent, pending approval by the doctor',
  evaluate: 'Evaluate',
  evaluatereservation: 'Evaluate Reservation',
  patientname: 'Patient Name',
  from: 'From',
  to: 'To',
  remove: 'Remove',
  newaccount: 'New Account',
  contanct: 'Contact',
  welcome1: 'connecting with your doctor makes your treatment easier',
  managefollowers: 'Manage Follower',
  welcome2: 'Book reservation for your family and friends',
  know: 'Know',
  welcome3: 'closest hospital near you',
  hospital: 'Hospital',
  graduationyear: 'Graduation Year',
  personalphoto: 'Personal Photo',
  universityphoto: 'University Photo',
  id_number: 'Nationality ID',
  nationality: 'Nationality',
  activateaccount: 'Activate Account',
  free: 'Free',
  attach: 'Attach',
  welcome4:
    'work under the supervision of specialists and consultants from Saudi universities for all nationalities',
  welcome5: 'Get notifications for your dates',
  prev: 'Previous',
  startnow: 'Start Now',
  autocomplete: 'Automatic activation when your receive massage on this phone',
  patient: 'Patient',
  doctor: 'Doctor',
  doctorID: 'Doctor ID',
  dob: 'Date of birth',
  sex: 'Sex',
  approveterms: 'Accept terms of use',
  confirmemail: 'Confirm Email Address',
  nextappointments: 'Next Appointments',
  prevappointments: 'Previous Appointments',
  preovidedservices: 'Provided Services',
  recentoffers: 'Recent Offers',
  sat: 'Saturday',
  sun: 'Sunday',
  mon: 'Monday',
  tue: 'Tuesday',
  wed: 'Wednesday',
  thu: 'Thursday',
  fri: 'Friday',
  appointment: 'Appointment',
  night: 'Night',
  medicine: 'Medicine',
  dentalfillings: 'Dental Fillings',
  gumtreatment: 'Gum Treatment',
  appointmentdetails: 'Appointment Details',
  reference: 'Reference',
  doctorname: 'Doctor Name',
  personalprofile: 'Personal Profile',
  picktimeanddate: 'Pick Time and Date',
  choose: 'Choose',
  nonotifications: 'No Notifications',
  contanctdoctor: 'Contanct Doctor',
  virtualhospital: 'Virtual Hospital',
  teba: 'Teba',
  bookdate: 'Book Date',
  messages: 'Messages',
  nomsgs: 'No Messages',
  hours24: '24 Hours',
  appointmentrefused: 'Appointment Refused By Doctor',
  appointmentrefusedPatient: 'Appointment Refused By Patient',
  hospitalname: 'Hospital Name',
  received: 'Received',
  offernmee: 'Offer Name',
  sometxt:
    'Some text for show Some text for show Some text for show Some text for show Some text for show ',
  fillings: 'Fillings',
  appointmentno: 'Appointment No#',
  enablenotifcations: 'Enable Notifcations',
  condition: 'Condition',
  waitingapprove: 'Waiting Approvement',
  attachments: 'Attachments',
  addref: 'Add Reference',
  chooseref: 'Choose Reference',
  referencename: 'Reference Name',
  relationType: 'Relation Type',
  friend: 'Friend',
  brother: 'Brother',
  husband: 'Husband',
  daughter: 'Daughter',
  son: 'Son',
  wife: 'Wife',
  father: 'Father',
  mother: 'Mother',
  choosemedicine: 'Choose Medicine',
  chooseHospital: 'Choose Hospital',
  takingmedences: 'Taking Medicines',
  haveillnes: 'Do you have diseases',
  password: 'Password',
  login: 'Login',
  home: 'Home',
  dontHaveAnAccount: "Don't have an account ?",
  signup: 'Register',
  createAcc: 'Create a New account',
  forgotPasswordQues: 'Forgot password!',
  confirm: 'Confirm',
  chooseDate: 'Choose appointment day',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Edit',
  update: 'Update',
  preferredLanugage: 'Preferred Lanugage',
  arabic: 'العربية',
  yes: 'Yes',
  no: 'No',
  email: 'Email Address',
  yourName: 'Name',
  phoneNumber: 'Phone Number',
  male: 'Male',
  female: 'Female',
  city: 'City',
  youHaveAcc: 'You have an account!',
  loginNow: 'Login Now',
  signupNow: 'Sign up Now',
  passwordConfirmation: 'Confirm Password',
  welcome: 'Welcome',
  homePharase: 'What you Looking for Today in Eventful !',
  service: 'Service',
  event: 'Event',
  ourServiceIn: 'Our Services in',
  selectServiceYouNeed: 'Select the service you would like to receive',
  specialOffer: 'Special Offer',
  submit: 'Submit',
  selectYourOffer:
    'Choose your offer as appropriate for your order by filling out the form below',
  approtType: 'Appropriate type',
  budget: 'Budget',
  fromRs: 'from RS',
  toRs: 'to RS',
  address: 'Address',
  notes: 'Notes',
  add: 'Add',
  ignore: 'Ignore',
  providerResponse: 'Provider Response',
  offerData: 'Your Offer Data',
  appropriatetype: 'Appropriate type',
  DateTime: 'Date  Time',
  editProfile: 'EditProfile',
  profile: 'Profile',
  PersonalData: 'Personal Data',
  ChangePassword: 'Change Password',
  paymentInfo: 'Payment Info',
  selectServiceYouWish: 'Select Services You Wish to get',
  viewProfile: 'View Profile',
  providers: 'Providers',
  providerData: 'Provider Data',
  details: 'Details',
  services: 'Services',
  priceRange: 'price range:',
  serviceData: 'Service Data',
  photos: 'Photos',
  getDirection: 'Get Direction',
  booking: 'Booking',
  events: 'Events',
  eventsPhase: 'Enjoy and join to Events',
  eventsRecently: 'Events Recently added',
  musicParty: 'Music Party',
  bookingNow: 'Booking now',
  selectServiceYouWish: 'Select Services You Wish to get',
  viewProfile: 'View Profile',
  providers: 'Providers',
  providerData: 'Provider Data',
  services: 'Services',
  priceRange: 'price range:',
  serviceData: 'Service Data',
  photos: 'Photos',
  location: 'Location',
  getDirection: 'Get Direction',
  booking: 'Booking',
  paymentInfo2: 'Your Payment Info',
  creditName: 'Credit name',
  CardNumber: 'Card Number',
  cardtype: 'card type',
  expirationDate: 'Expiration Date',
  month: 'MM',
  Year: 'YYYY',
  numOfComments: '{0} comments',
  reviews: 'Reviews',
  addReview: 'Add Review',
  templates: 'Templates',
  templatesPhase: 'You can invite anyone to Event',
  editTemplates: 'Edit Template',
  invitation: 'Invitations',
  mainTitle: 'Main Title',
  invitationText: 'Invitation Text',
  invitationDate: 'Invitation Date',
  telephone: 'Telephone',
  ownerOfInvitation: 'The owner of the invitation',
  addFriends: 'Add Your Friends',
  view: 'View',
  viewTemplates: 'View Template',
  shareDoctorCard: 'Share Dentist Card',
  language: 'Language',
  english: 'English',
  arabic: 'Arabic',
  aboutApp: 'About Application',
  aboutDev: 'About the developer',
  termsAndCond: 'Terms And Conditions',
  customerService: 'customers service',
  settings: 'Settings',
  langPhase: 'Choose the Language of Application',
  contactUs: 'Contact us',
  termsPhase: 'Terms And Conditions',
  termsRead:
    'Read the following Terms of Use carefully before using this Application.',
  message: 'Message',
  customerPhase:
    'Stay in touch with us and let us know your comments and complaints',
  forgetPasswordPhase:
    "Enter your email and we'll send you a confirmation code to set your password",
  forgetPassword: 'Forget Password',
  confirmationCode: 'Confirmation Code',
  confirmPhase: 'Your confirmation code has been sent. Please check your inbox',
  sendCode: 'Send code',
  confirmCode: 'Confirm Code',
  sendCodeAgain: 'Send Code Again',
  newPassword: 'New Password',
  enterNewpassword: 'Please Enter Your New Password',
  organizers: 'Organizers',
  eventData: 'Event data',
  book: 'Book',
  seeAll: 'See All',
  yourPurches: 'Your Purchase',
  serviceTotal: 'Service total',
  eventTicketesTotal: 'Event Ticket Total',
  orderTotal: 'Order total',
  payWith: 'Pay With',
  addNewPayment: 'Add New Payment info',
  basket: 'Basket',
  goTo: 'Go to',
  notifications: 'Notifications',
  search: 'Search',
  almostDone: 'Almost Done',
  yourOrderAdded: 'Your Order added to Your Card',
  gotoCard: 'Go to card',
  keepBrowsing: 'keep browsing',
  bookingFor: 'Booking For',
  orderMadeTo: 'Your reservation will be made to :',
  forFemale: 'For Female only',
  forMale: 'For Male only',
  next: 'Next',
  share: 'Share With',
  asInvitation: 'as  Invitation',
  or: 'or',
  audioList: 'Audio List Album',
  albums: 'Albums',
  simmilerAlbums: 'Simmilar Albums',
  giveReview: 'Give A Review',
  reviewPhase: 'You Can Rate by Use the Stars',
  reviewLabel: 'Tell Us More',
  writeComment: 'Write a Comment',
  thankYou: 'Thank You',
  successProcess: 'Successful process',
  billDate: 'Bill Date',
  time: 'Time',
  total: 'Total',
  oprationNum: 'operation Number',
  done: 'Done',
  RS: '{0} RS',
  likeCount: '{0} like',
  joinCount: '{0} join',
  reload: 'Reload',
  logout: 'Logout',
  noServicesFound: 'No services found',
  downloadOnThe: 'Download on the',
  googlePlay: 'Google Play',
  appStore: 'App Store',
  code: 'code',
  morning: 'morning',
  az: ' Azerbaijan',
  am: ' Armenia',
  es: ' Spain',
  au: ' Australia',
  af: ' Afghanistan',
  al: ' Albania',
  de: ' Germany',
  ag: ' Antigua and Barbuda',
  ao: ' Angola',
  ai: ' Anguilla',
  ad: ' Andorra',
  uy: ' Uruguay',
  uz: ' Uzbekistan',
  ug: ' Uganda',
  ua: ' Ukraine',
  ie: ' Ireland',
  is: ' Iceland',
  et: ' Ethiopia',
  er: ' Eritrea',
  ee: ' Estonia',
  ar: ' Argentina',
  jo: ' Jordan',
  ec: ' Ecuador',
  ae: ' The United Arab Emirates',
  bs: ' The Bahamas',
  bh: ' Bahrain',
  br: ' Brazil',
  pt: ' Portugal',
  ba: ' Bosnia and Herzegovina',
  ga: ' Gabon',
  me: ' the black Mountain',
  dz: ' Algeria',
  dk: ' Denmark',
  cv: ' green head',
  sv: ' El Salvador',
  sn: ' Senegal',
  sd: ' Sudan',
  se: ' Sweden',
  eh: ' Western Desert',
  so: ' Somalia',
  cn: ' China',
  iq: ' Iraq',
  va: ' Vatican',
  ph: ' Philippines',
  aq: ' South Pole',
  cm: ' Cameroon',
  cg: ' Congo - Brazzaville',
  kw: ' Kuwait',
  hu: ' Hungary',
  io: ' British Indian Ocean',
  ma: ' Morocco West sunset',
  tf: ' French Southern Territories',
  mx: ' Mexico',
  sa: ' Saudi Arabia',
  gb: ' United kingdom',
  nor: ' Norway',
  at: ' Austria',
  ne: ' Niger',
  in: ' India',
  us: ' United States of America',
  jp: ' Japan',
  ye: ' To whom',
  gr: ' Greece',
  id: ' Indonesia',
  ir: ' Iran',
  it: ' Italy',
  pg: ' Papua New Guinea',
  py: ' Paraguay',
  pk: ' Pakistan',
  pw: ' Palau',
  bw: ' Botswana',
  pn: ' Bitcairn',
  bb: ' Barbados',
  bm: ' Bermuda',
  bn: ' Brunei',
  be: ' Belgium',
  bg: ' Bulgaria',
  bz: ' Belize',
  bd: ' Bangladesh',
  pa: ' Panama',
  bj: ' Boys',
  bt: ' Bhutan',
  pr: ' Puerto Rico',
  bf: ' Burkina Faso',
  bi: ' Burundi',
  pl: ' Poland',
  bo: ' Bolivia',
  pf: ' French Polynesia',
  pe: ' Peru',
  tz: ' Tanzania',
  th: ' Thailand',
  tw: ' Taiwan',
  tm: ' Turkmenistan',
  tr: ' Turkey',
  tt: ' Trinidad and Tobago',
  td: ' Chad',
  tg: ' Togo',
  tv: ' Tuvalu',
  tk: ' Tokelau',
  to: ' Tonga',
  tn: ' Tunisia',
  tl: ' East Timor',
  jm: ' Jamaica',
  gi: ' Tarek mountain',
  gd: ' Grenada',
  gl: ' Green Land',
  ax: ' Ulan Islands',
  an: ' Netherlands Antilles',
  tc: ' Turks and Caicos Islands',
  km: ' Island of the Moon',
  ky: ' Cayman Islands',
  mh: ' Marshall Islands',
  mv: ' Maldives',
  um: ' United States Minor Outlying Islands',
  sb: ' Solomon Islands',
  fo: ' Faroe Islands',
  vi: ' US Virgin Islands',
  vg: ' British Virgin Islands',
  fk: ' Falkland Islands',
  ck: ' Cook Islands',
  cc: ' Cocos Islands',
  mp: ' Northern Mariana Islands',
  wf: ' Wallis and Futuna Islands',
  cx: ' Christmas Island',
  bv: ' Buffet Island',
  im: ' Isle of Man',
  nf: ' Norfolk Island',
  hm: ' Heard Island and McDonald',
  cf: ' Central African Republic',
  cz: ' Czech Republic',
  do: ' Dominican Republic',
  cd: ' Democratic Republic of the Congo',
  za: ' Republic of South Africa',
  gt: ' Guatemala',
  gp: ' Guadeloupe',
  gu: ' Guam',
  ge: ' Georgia',
  gs: ' South Georgia and the South Sandwich Islands',
  dj: ' Djibouti',
  je: ' Jersey',
  dm: ' Dominica',
  rw: ' Rwanda',
  ru: ' Russia',
  by: ' White Russia',
  ro: ' Romania',
  re: ' Reunion',
  zm: ' Zambia',
  zw: ' Zimbabwe',
  ci: " Cote d'Ivoire",
  ws: ' Samoa',
  as: ' American Samoa',
  sm: ' San Marino',
  pm: ' St. Pierre and Miquelon',
  vc: ' Saint Vincent and the Grenadines',
  kn: ' Saint Kitts and Nevis',
  lc: ' St. Lucia',
  mf: ' St. Martin',
  sh: ' St. Helena',
  st: ' Sao Tome and Principe',
  lk: ' Sri Lanka',
  sj: ' Svalbard and Jan Mayen',
  sk: ' Slovakia',
  si: ' Slovenia',
  sg: ' Singapore',
  sz: ' Swaziland',
  sy: ' Syria',
  sr: ' Suriname',
  ch: ' Switzerland',
  sl: ' Sierra Leone',
  sc: ' Seychelles',
  cl: ' Chilean',
  rs: ' Serbia',
  cs: ' Serbia and Montenegro',
  tj: ' Tajikistan',
  om: ' Oman',
  gm: ' The Gambia',
  gh: ' Ghana',
  gf: ' Guyana',
  gy: ' Guyana',
  gn: ' Guinea',
  gq: ' Equatorial Guinea',
  gw: ' Guinea-Bissau',
  vu: ' Vanuatu',
  fr: ' France',
  ps: ' Palestine',
  ve: ' Venezuela',
  fi: ' Finland',
  vn: ' Vietnam',
  fj: ' Fiji',
  cy: ' Cyprus',
  kg: ' Kyrgyzstan',
  qa: ' Diameter',
  kz: ' Kazakhstan',
  nc: ' New Caledonia',
  hr: ' Croatia',
  kh: ' Cambodia',
  ca: ' Canada',
  cu: ' Cuba',
  kr: ' South Korea',
  kp: ' North Korea',
  cr: ' Costa Rica',
  co: ' Colombia',
  ki: ' Kiribati',
  ke: ' Kenya',
  lv: ' Latvia',
  la: ' Laos',
  lb: ' Lebanon',
  lu: ' Luxembourg',
  ly: ' Libya',
  lr: ' Liberia',
  lt: ' Lithuania',
  li: ' Liechtenstein',
  ls: ' Lesotho',
  mq: ' Martinique',
  mo: ' Macau Chinese',
  mt: ' Malta',
  ml: ' Financial',
  my: ' Malaysia',
  yt: ' Mayotte',
  mg: ' Madagascar',
  eg: ' Egypt',
  mk: ' Macedonia',
  mw: ' Malawi',
  mn: ' Mongolia',
  mr: ' Mauritania',
  mu: ' Mauritius',
  mz: ' Mozambique',
  md: ' Moldova',
  mc: ' Monaco',
  ms: ' Montserrat',
  mm: ' Myanmar',
  fm: ' Micronesia',
  na: ' Namibia',
  nr: ' Nauru',
  np: ' Nepal',
  ng: ' Nigeria',
  ni: ' Nicaragua',
  nz: ' New Zealand',
  nu: ' Niue',
  ht: ' Haiti',
  hn: ' Honduras',
  nl: ' Holland',
  hk: ' Hong Kong Chinese',
  enterCodeSentPhone: 'Enter the code sent to your phone',
  enterCodeCorrect: 'enter correct code',
  TaxNumber: 'TaxNumber',
  AttachTaxFile: 'Attach the tax number document',
  CommercialRegistrationNo: 'Commercial Registration No',
  AttachCommercialFile: 'Attach the commercial registration number document',
  ChamberOfCommerceNo: 'Chamber of Commerce No',
  AttachChamberFile: 'Attach the Chamber of Commerce number document',
  BankAccountNumber: 'Bank account number',
  BankName: 'Bank name',
  AttachBankAccountFile: 'Attach the bank account number document',
  chooseImage: 'Choose image',
  camera: 'Camera',
  library: 'Library',
  collaboratingCoaches: 'We are looking for collaborating coaches',
  LookingCooperation: 'Looking for a training center for cooperation',
  education: 'Education',
  experience: 'Experience',
  Enterprise: 'Enterprise',
  Place: 'Place',
  Degree: 'Degree',
  Achievements: 'Achievements',
  JobTitle: 'Job title',
  noDegrees: 'No found degrees',
  MoreOfficialPapers: 'More official papers',
  fileTitle: 'File title',
  attachFile: 'Attach file',
  hallCapacity: 'Hall capacity',
  buildingNumber: 'Building number',
  DescriptionHall: 'Description of the hall',
  accreditatioBody: 'Accreditation body',
  accreditationNo: 'Accreditation No.',
  accreditationCertificate: 'Accreditation Certificate',
  discountDay: 'Discount for booking more than one day (Price)',
  numberDaysDiscount: 'Number of days to get the discount',
  keywords: 'Keywords',
  profileImage: 'Profile image',
  hallImages: 'Hall images',
  hallCharacteristics: 'Hall characteristics',
  HallCredences: 'Hall credences',
  CourseTitle: 'Course title',
  Languages: 'Languages',
  ChooseArea: 'Choose a course area',
  ChooseProgram: 'Choose the training program',
  TheNumberHours: 'The number of hours',
  TheNumberDays: 'The number of days',
  Category: 'Category',
  AttachTheCourseAnnouncement: 'Attach the course announcement',
  CourseCredits: 'Course credits',
  CourseCoach: 'Course coach',
  HallName: 'Hall name',
  TargetGroup: 'Target group',
  NumberAvailable: 'Number of seats available',
  theLevel: 'The level',
  junior: 'junior',
  Average: 'Average',
  advanced: 'Advanced',
  DescriptionDetails: 'Description and details',
  ExternalLink: 'External link',
  CourseFeatures: 'Course Features',
  hallFeatures: 'Hall Features',
  Trainer: 'Trainer',
  TrainerName: 'Trainer name',
  men: 'Men',
  Ladies: 'Ladies',
  menAndLadies: 'Men and ladies',
  EarlyCancellationDate: 'Early cancellation date',
  EarlyCancellationTime: 'Early cancellation time',
  DeductionForLateCancellation: 'Deduction for late cancellation',
  selectedAll: 'Selecte all',
  skipLogin: 'Skip login',
  password_not_match: 'Passwords not matches',
  app: 'Ertaqee',
  confirm_delete:
    'Are you sure to permanently delete this with existing individuals?',
  cancel: 'Cancel',
  ok: 'Ok',
  edit_trainee: 'Edit trainee',
  email_not_valid: 'Email not valid',
  changePassword: 'Change password',
  chooseHowToChange: 'Verification code will send to ?',
  sendToMobile: 'Send to mobile number',
  sendToEmail: 'Send to email address',
  currentPassword: 'Current password',
  choose_trainer: 'Choose trainers',
  student_num: 'Student number:',
  loginFirst: 'You must login first',
  send_request: 'Ask for cooperation',
  request_send: 'Ask for cooperation send successfully',
  editStudent: 'Edit user',
  all: 'All',
  up_to_data: "It's too late to book",
  accept_terms: ' Accept terms and conditions',
  course_setting: ' Course settings',
  choose_country: 'Choose country',
  choose_city: 'Choose city',
  too: 'To',
  company_name: 'Company name',
  build_name: 'Facility Name',
  hall_type: 'Hall service provider type',
  company_size: 'Facility size',
  already_exsist: 'Item already exist in cart.',
  cart_retrieved: 'Cart retrieved Successfully',
  number_of_attendees: 'Number of attendees: ',
  reservtions_halls: 'Halls reservations',
  CourseFeild: 'Field of training courses',
  courses_reser: 'Halls orders',
  student_price: 'Price per person: ',
  hello: 'Hello',
  morning: 'Good Morning ☀',
  afternoon: 'Good Afternoon ⛅',
  evening: 'Good Evening 🌙',
  enterUsername: 'Just enter the username and password to continue logging in',
  '': '',
  select: 'Select',
  bestTrainingCenters: 'Best training center',
  newCources: 'New Courses',
  restoreByEmail: 'Password recovery with mobile phone number',
  restoreByPhone: 'Password recovery with email',
  gender: ' Gender',
  hallStatus: 'Hall status',
  hallDetails: 'Details',
  editHall: 'Edit hall',
  editCourse: 'Edit course',
  deleteAccount: 'Delete account',
  deleteAccountDone: 'Delete account done successfully',
  deleteAccountConfirm: 'Are you sure you want to delete this account?',
  InfoAboutMe: 'Info about me',
  skills: 'Skills',
  soon: 'Soon',
  pay: 'Pay',
  centerType: 'Center type',
  rate:'Rate',
  cv: 'CV file'
};
